### PR TITLE
Adding aarch64 CPU feature detection for FreeBSD

### PR DESCRIPTION
**Pull request by Martyrshot**
This PR adds aarch64 CPU feature detection support when compiling for FreeBSD.

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by Martyrshot** [comment]
Currently there is a linking problem with SIKE asm. My guess is that it isn't *exclusively* SIKE that is having the problem, it's just the first point of failure and thus is stopping compilation.

Note, in order to build on FreeBSD 13, there needs to be some type casts added to tests/ds_benchmark.h. It looks like the port that gets built on FreeBSD accounts for this, so I didn't push the change to this PR. I can if others think it's a good idea.

In order to build the version being discussed in #1208 do the the following:

liboqs dependencies:
```
pkg install git python3 openssl py38-pytest py38-pytest-xdist gcc astyle-3.1_3 ninja-1.10.2,2 unzip libxslt-1.1.35_2 doxygen-1.9.3,2 graphviz-2.50.0_1 py38-yaml-5.4.1 cmake-3.22.2
```

Fetch ports:
```
portsnap fetch
portsnap extract
```

Build:
```
cd /usr/ports/security/liboqs
```
comment out line 13 in `Makefile`
```
make
```
This will fail with the issue described in #1208, but will make a `work/` directory. 
```
cd work/liboqs-0.7.1
git checkout jg-freebsd-cpu-features
cd ../.build && ninja
```

Current compilation error output: 

```
[1/19] Linking C executable tests/test_kem
FAILED: tests/test_kem
: && /usr/bin/cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -Wl,-rpath,/usr/local/lib -fstack-protector-strong tests/CMakeFiles/test_kem.dir/test_kem.c.o -o tests/test_kem  -Wl,-rpath,/usr/ports/security/liboqs/work/.build/lib:/usr/local/lib  lib/liboqs.so.0.7.1  -lm  /usr/local/lib/libcrypto.so  -pthread && :
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub434_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub434_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub503_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub503_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub610_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub610_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub751_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub751_p4_asm [--no-allow-shlib-undefined]
ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[2/19] Linking C executable tests/kat_kem
FAILED: tests/kat_kem
: && /usr/bin/cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -Wl,-rpath,/usr/local/lib -fstack-protector-strong tests/CMakeFiles/kat_kem.dir/kat_kem.c.o -o tests/kat_kem  -Wl,-rpath,/usr/ports/security/liboqs/work/.build/lib:/usr/local/lib  lib/liboqs.so.0.7.1  -lm  /usr/local/lib/libcrypto.so && :
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub434_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub434_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub503_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub503_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub610_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub610_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub751_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub751_p4_asm [--no-allow-shlib-undefined]
ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[3/19] Linking C executable tests/example_kem
FAILED: tests/example_kem
: && /usr/bin/cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -Wl,-rpath,/usr/local/lib -fstack-protector-strong tests/CMakeFiles/example_kem.dir/example_kem.c.o -o tests/example_kem  -Wl,-rpath,/usr/ports/security/liboqs/work/.build/lib:/usr/local/lib  lib/liboqs.so.0.7.1  -lm  /usr/local/lib/libcrypto.so && :
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub434_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub434_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc434_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub503_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub503_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc503_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub610_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub610_p4_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpadd610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_fpsub610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mul610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_rdc610_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub751_p2_asm [--no-allow-shlib-undefined]
ld: error: lib/liboqs.so.0.7.1: undefined reference to oqs_kem_sike_mp_sub751_p4_asm [--no-allow-shlib-undefined]
ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by baentsch** [comment]
FYI, trying to reproduce... As local setup of a FreeBSD instance hits one issue after the next (or I simply don't understand FreeBSD using qemu-arm on x64... :) I'll be setting up an AWS ARM64 FreeBSD13 instance based on a standard FreeBSD13 AMI. If OK (@dstebila ?) we could keep this image around (stopped) until someone needs it for debugging again along the lines of the chromium build image....

**Comment by Martyrshot** [comment]
It took me an embarrassing amount of time to get FreeBSD 13 working in parallels, so I can only imagine trying to spin it up on qemu. 😄

**Comment by baentsch** [comment]
The FreeBSD13 AMI spin-up was painless and I could follow all your steps up to 
`cd work/liboqs-0.7.1 && git checkout jg-freebsd-cpu-features`. Then things broke: There's no `.git` (and hence, no connection to github and no way to check out "jg-freebsd-cpu-features") in that folder. 

@Martyrshot, @yurivict  : What else does one have (need) to do to get to check out another branch in this "ports/security" directory structure? Or what could I have done wrong to not have downloaded the ".git" directory when running the `portsnap` commands? Pardon the possibly silly questions but I have no prior experience with FreeBSD.

After manually moving a fresh checkout of `liboqs` into the same location (`mv liboqs-0.7.1 liboqs-0.7.1.orig && git clone https://github.com/open-quantum-safe/liboqs.git && mv liboqs liboqs-0.7.1 && cd liboqs-0.7.1 && git checkout jg-freebsd-cpu-features`) the `ninja` command started, but it seems it didn't pick up the newly added `__FREEBSD__` define: Reading up on ["things FreeBSD"](https://docs.freebsd.org/en/books/porters-handbook/porting-dads/#porting-versions) it seems one needs to add `#include <sys/param.h>` to be able to use that define. After doing that, all hell broke loose: This defines "ALIGN" which is redefined by some OQS algorithms...

@Martyrshot : How did you get your install to set the `__FREEBSD__` define?

**Comment by Martyrshot** [comment]
> @Martyrshot, @yurivict : What else does one have (need) to do to get to check out another branch in this "ports/security" directory structure? Or what could I have done wrong to not have downloaded the ".git" directory when running the `portsnap` commands? Pardon the possibly silly questions but I have no prior experience with FreeBSD.

Looks like I misremembered my steps a bit. I had to copy the modified file manually as well. Sorry about that.
 
> but it seems it didn't pick up the newly added __FREEBSD__ define

Just to clarify did the build fail on this define,  or did something else happen? I didn't have to define `__FREEBSD__` do anything to get past this step. I haven't done proper testing to see if features were detected properly since I got the above linking issue.

I made a quick test to see if my install FreeBSD had it defined for some reason, but it appears it doesn't either so I'm a bit confused why the liboqs build in ports gets past compiling common.c at all. 

It looks like `__FreeBSD__` is set (verified by compiling my test c program), so I updated the branch to use that variable. Hopefully that resolves the issue you are experiencing.

**Comment by baentsch** [comment]
> It looks like __FreeBSD__ is set (verified by compiling my test c program), so I updated the branch to use that variable. Hopefully that resolves the issue you are experiencing.

Thanks! It does: Unlike `__FREEBSD__` the define `__FreeBSD__` indeed is set so your new code gets compiled now. Unfortunately, compilation now fails like this:

```
FAILED: src/common/CMakeFiles/common.dir/common.c.o 
/usr/bin/cc  -I/usr/ports/security/liboqs/work/.build/include -I/usr/local/include -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -fPIC -fvisibility=hidden -Werror -Wall -Wextra -Wpedantic -Wno-unused-command-line-argument -O3 -fomit-frame-pointer -Wbad-function-cast -Wcast-qual -Wnarrowing -Wconversion -std=gnu11 -MD -MT src/common/CMakeFiles/common.dir/common.c.o -MF src/common/CMakeFiles/common.dir/common.c.o.d -o src/common/CMakeFiles/common.dir/common.c.o -c /usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c
/usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c:99:19: error: use of GNU statement expression extension [-Werror,-Wgnu-statement-expression]
        uint64_t isar0 = READ_SPECIALREG(id_aa64isar0_el1);
                         ^
/usr/include/machine/armreg.h:63:2: note: expanded from macro 'READ_SPECIALREG'
({      uint64_t _val;                                                  \
 ^
/usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c:106:38: error: use of undeclared identifier 'ID_AA64ISAR0_SHA3_BASE'
        if (ID_AA64ISAR0_SHA3_VAL(isar0) >= ID_AA64ISAR0_SHA3_BASE) {
                                            ^
/usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c:109:6: error: implicit declaration of function 'ID_AA64ISAR0_AdvSIMD_VAL' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (ID_AA64ISAR0_AdvSIMD_VAL(isar0) >= ID_AA64ISAR0_AdvSIMD_BASE) {
            ^
/usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c:109:41: error: use of undeclared identifier 'ID_AA64ISAR0_AdvSIMD_BASE'; did you mean 'ID_AA64ISAR0_AdvSIMD_VAL'?
        if (ID_AA64ISAR0_AdvSIMD_VAL(isar0) >= ID_AA64ISAR0_AdvSIMD_BASE) {
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~
                                               ID_AA64ISAR0_AdvSIMD_VAL
/usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c:109:6: note: 'ID_AA64ISAR0_AdvSIMD_VAL' declared here
        if (ID_AA64ISAR0_AdvSIMD_VAL(isar0) >= ID_AA64ISAR0_AdvSIMD_BASE) {
            ^
4 errors generated.

```

--> Looks like the proposed solution is GNU-specific and `-Wall` flags this code.... Have you tried with `clang`?

```
root@freebsd:/usr/ports/security/liboqs # cc --version
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
Target: aarch64-unknown-freebsd13.1
Thread model: posix
InstalledDir: /usr/bin
```

If you'd want to log in to this VM to have access to the ready-made environment, please send me your ssh public key (or ask @dstebila to add you to the ACL for the OQS-AWS VM named "Dev-FreeBSD-ARM64").

**Comment by dstebila** [comment]
@Martyrshot any updates on this?

**Comment by Martyrshot** [comment]
It looks like I have resolved the primary FreeBSD issue. Just to confirm, is SIKE is pulled in manually from upstream and not from one of our scripts? It looks like that's the case, but before saying this PR is good to go I thought I would double check.

**Comment by baentsch** [comment]
> SIKE is pulled in manually from upstream and not from one of our scripts

That statement is correct. Last such event if I remember correctly: #1079

**Comment by Martyrshot** [comment]
Ok, great. Then this PR should be good to go.

One thing worth talking about though is that I noticed in the SIKE documentation that only Darwin and Linux are listed as supported platforms. In order to get SIKE to build I had to explicitly add "FreeBSD" ([here](https://github.com/open-quantum-safe/liboqs/blob/f5141a0ff6c4937d757f516e92731ac5f771647c/src/kem/sike/CMakeLists.txt#L77)) to CMakeLists.txt. All tests pass so it looks like it's fine, but is this a case of not fixing and telling FreeBSD users to disable SIKE, or should we update the documentation to list FreeBSD as a supported platform?

**Comment by baentsch** [comment]
> do we want to include the added type casts in tests/ds_benchmark.h in this pr? Right now the PR doesn't include them as they don't seem to be part of the issue in the FreeBSD ports, but while working on this implicit typecasting warnings were output so it might be worth updating while we are here?

I know, I know, one shouldn't answer questions not directed at oneself, but here I can't remain silent: If you're seeing something wrong (and a compiler confirms you in this :-), I'd favour fixing it. My suggestion would be to do it in a separate PR, though, to keep changes "to the point" (and aid understanding by a reviewer). So, I'd suggest getting this PR's CI "green", reviewing and closing this PR and do the same fixing benchmarking

**Comment by baentsch** [comment]
@Martyrshot Could you please re-base the PR on the latest "main"? CI should then pass and you could move this to "Review" (assuming this is complete as-is).

**Comment by Martyrshot** [comment]
> @Martyrshot Could you please re-base the PR on the latest "main"? CI should then pass and you could move this to "Review" (assuming this is complete as-is).

There appears to be another picnic issue with msys2? I don't believe any changes I've done would cause this issue to pop up. Since yuri has confirmed that there are no longer and build failures on freebsd arm64, I think this PR is ready for review.

**Review by dstebila — APPROVED** [review]
