### ISSUE TITLE
Build failure on macOS Sierra 

### ISSUE THREAD

**Issue by andersonDadario** [open-quantum-safe/liboqs#208]
Hello,

I tried to build on macOS Sierra 10.12.6 following the procedures on Readme:

`$ brew install autoconf automake cmake libtool`

Warning: autoconf 2.69 is already installed
Warning: automake 1.15.1 is already installed
Warning: cmake 3.10.1 is already installed
Warning: libtool 2.4.6_1 is already installed

```
autoreconf -i
./configure
make clean
make
```

But I got a file not found (picnic.h) as you can see below:

`$ make`

(...)
Making all in src/sig_picnic
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -march=native -I../../include -Iexternal -Iexternal/build -DENABLE_KEX_LWE_FRODO -DENABLE_KEX_MLWE_KYBER -DENABLE_KEX_NTRU -DENABLE_KEX_RLWE_MSRLN16 -DENABLE_KEX_RLWE_NEWHOPE -DENABLE_KEX_SIDH_CLN16 -DENABLE_SIG_PICNIC -g -std=gnu11 -Wno-unused-function -Werror -Wpedantic -Wall -Wextra -DCONSTANT_TIME -DAES_ENABLE_NI   -g -O2 -c -o libpicnic_i_la-sig_picnic.lo `test -f 'sig_picnic.c' || echo './'`sig_picnic.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -march=native -I../../include -Iexternal -Iexternal/build -DENABLE_KEX_LWE_FRODO -DENABLE_KEX_MLWE_KYBER -DENABLE_KEX_NTRU -DENABLE_KEX_RLWE_MSRLN16 -DENABLE_KEX_RLWE_NEWHOPE -DENABLE_KEX_SIDH_CLN16 -DENABLE_SIG_PICNIC -g -std=gnu11 -Wno-unused-function -Werror -Wpedantic -Wall -Wextra -DCONSTANT_TIME -DAES_ENABLE_NI -g -O2 -c sig_picnic.c -o libpicnic_i_la-sig_picnic.o
sig_picnic.c:8:10: fatal error: 'picnic.h' file not found
#include "picnic.h"
         ^~~~~~~~~~
1 error generated.
make[2]: *** [libpicnic_i_la-sig_picnic.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I wonder whether this is an error or whether I am doing something wrong.

**Comment by andersonDadario** [comment]
My bad, I had to clone with --recursive:

`$ git clone --recursive https://github.com/open-quantum-safe/liboqs`
