### ISSUE TITLE
Many schemes fail to compile with GCC 11.1.0

### ISSUE THREAD

**Issue by thomwiggers** [open-quantum-safe/liboqs#1035]
After the SIKE issues in #1003 I saw that:

* [x] #1036
```
FAILED: src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o
/usr/bin/cc  -Iinclude -I../src/kem/classic_mceliece/pqclean_mceliece348864_avx -I../src/common/pqclean_shims -fPIC -fvisibility=hidden -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -mavx2 -mpopcnt -Wno-language-extension-token -std=gnu11 -MD -MT src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o -MF src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o.d -o src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o -c ../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.c
../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.c:351:47: error: argument 1 of type ‘vec128[12]’ {aka ‘__m128i[12]’} with mismatched bound [-Werror=array-parameter=]
  351 | void PQCLEAN_MCELIECE348864_AVX_fft_tr(vec128 out[GFBITS], vec256 in[][ GFBITS ]) {
      |                                        ~~~~~~~^~~~~~~~~~~
In file included from ../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.c:6:
../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.h:11:40: note: previously declared as ‘vec128 *’ {aka ‘__m128i *’}
   11 | void PQCLEAN_MCELIECE348864_AVX_fft_tr(vec128 * /*out*/, vec256  /*in*/[][ GFBITS ]);
      |                                        ^~~~~~~~
```

* [ ] Kyber has problems

```
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:557:64: error: argument 3 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} declared as a pointer [-Werror=array-parameter=]
  557 | void aes256ctr_prf(uint8_t *out, size_t outlen, const uint8_t *key, const uint8_t *nonce)
      |                                                 ~~~~~~~~~~~~~~~^~~
In file included from ../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:27:
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.h:19:34: note: previously declared as an array ‘const uint8_t[32]’ {aka ‘const unsigned char[32]’}
   19 |                    const uint8_t key[32],
      |                    ~~~~~~~~~~~~~~^~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:557:84: error: argument 4 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} declared as a pointer [-Werror=array-parameter=]
  557 | void aes256ctr_prf(uint8_t *out, size_t outlen, const uint8_t *key, const uint8_t *nonce)
      |                                                                     ~~~~~~~~~~~~~~~^~~~~
In file included from ../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:27:
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.h:20:34: note: previously declared as an array ‘const uint8_t[12]’ {aka ‘const unsigned char[12]’}
   20 |                    const uint8_t nonce[12]);
      |                    ~~~~~~~~~~~~~~^~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:565:54: error: argument 2 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} declared as a pointer [-Werror=array-parameter=]
  565 | void aes256ctr_init(aes256ctr_ctx *s, const uint8_t *key, const uint8_t *nonce)
      |                                       ~~~~~~~~~~~~~~~^~~
In file included from ../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:27:
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.h:24:35: note: previously declared as an array ‘const uint8_t[32]’ {aka ‘const unsigned char[32]’}
   24 |                     const uint8_t key[32],
      |                     ~~~~~~~~~~~~~~^~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:565:74: error: argument 3 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} declared as a pointer [-Werror=array-parameter=]
  565 | void aes256ctr_init(aes256ctr_ctx *s, const uint8_t *key, const uint8_t *nonce)
      |                                                           ~~~~~~~~~~~~~~~^~~~~
In file included from ../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:27:
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.h:25:35: note: previously declared as an array ‘const uint8_t[12]’ {aka ‘const unsigned char[12]’}
   25 |                     const uint8_t nonce[12]);
      |                     ~~~~~~~~~~~~~~^~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c: In function ‘aes_ctr4x’:
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:415:19: error: array subscript 112 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  415 |         q[0] ^= sk[0];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:416:19: error: array subscript 113 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  416 |         q[1] ^= sk[1];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:417:19: error: array subscript 114 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  417 |         q[2] ^= sk[2];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:418:19: error: array subscript 115 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  418 |         q[3] ^= sk[3];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:419:19: error: array subscript 116 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  419 |         q[4] ^= sk[4];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:420:19: error: array subscript 117 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  420 |         q[5] ^= sk[5];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:421:19: error: array subscript 118 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  421 |         q[6] ^= sk[6];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:422:19: error: array subscript 119 is outside array bounds of ‘uint64_t[64]’ {aka ‘long unsigned int[64]’} [-Werror=array-bounds]
  422 |         q[7] ^= sk[7];
      |                 ~~^~~
../src/kem/kyber/pqcrystals-kyber_common_ref/aes256ctr.c:486:67: note: while referencing ‘sk_exp’
  486 | static void aes_ctr4x(uint8_t out[64], uint32_t ivw[16], uint64_t sk_exp[64])
      |                                                          ~~~~~~~~~^~~~~~~~~~
```

* [ ] NTRU has problems

```
FAILED: src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o
/usr/bin/cc  -Iinclude -I../src/kem/ntru/pqclean_ntruhps2048677_avx2 -I../src/common/pqclean_shims -fPIC -fvisibility=hidden -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -mavx2 -mbmi2 -std=gnu11 -MD -MT src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o -MF src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o.d -o src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o -c ../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c
../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:3:64: error: argument 1 of type ‘unsigned char[272]’ with mismatched bound [-Werror=array-parameter=]
    3 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_tobytes(unsigned char msg[NTRU_OWCPA_MSGBYTES], const poly *a) {
      |                                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:1:
../src/kem/ntru/pqclean_ntruhps2048677_avx2/poly.h:25:64: note: previously declared as ‘unsigned char[136]’
   25 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_tobytes(unsigned char msg[NTRU_PACK_TRINARY_BYTES], const poly *a);
      |                                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:24:81: error: argument 2 of type ‘const unsigned char[272]’ with mismatched bound [-Werror=array-parameter=]
   24 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_OWCPA_MSGBYTES]) {
      |                                                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:1:
../src/kem/ntru/pqclean_ntruhps2048677_avx2/poly.h:26:81: note: previously declared as ‘const unsigned char[136]’
   26 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_PACK_TRINARY_BYTES]);
      |                                                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

* [ ] Dilithium has problems

```
FAILED: src/sig/dilithium/CMakeFiles/dilithium_2_aes_avx2.dir/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c.o
/usr/bin/cc  -Iinclude -I../src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2 -I../src/common/pqclean_shims -fPIC -fvisibility=hidden -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -mavx2 -maes -mpopcnt -DDILITHIUM_MODE=2 -DDILITHIUM_USE_AES -DDILITHIUM_RANDOMIZED_SIGNING -std=gnu11 -MD -MT src/sig/dilithium/CMakeFiles/dilithium_2_aes_avx2.dir/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c.o -MF src/sig/dilithium/CMakeFiles/dilithium_2_aes_avx2.dir/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c.o.d -o src/sig/dilithium/CMakeFiles/dilithium_2_aes_avx2.dir/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c.o -c ../src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c
In file included from ../src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2/params.h:4,
                 from ../src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c:5:
../src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c: In function ‘pqcrystals_dilithium2aes_avx2_poly_uniform_eta_preinit’:
../src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2/config.h:18:32: error: ‘pqcrystals_dilithium2aes_avx2_rej_eta_avx’ reading 768 bytes from a region of size 192 [-Werror=stringop-overread]
```

**Comment by thomwiggers** [comment]
I accidentally clicked the "turn checkbox into task" button 🤷🏻

**Comment by koraa** [comment]
For anyone else stumbling on this; compiling with clang works

    CC=clang cargo build

**Comment by baentsch** [comment]
FWIW: `cygwin` seems to have upgraded by default to GCC11, triggering [this Appveyor failure](https://ci.appveyor.com/project/dstebila/liboqs/builds/40682266/job/ulj3g4nod20c57bd) making resolution of this issue more urgent. Alternative: Force use of GCC<11...

**Comment by dstebila** [comment]
@bhess Would you be able to look at the Kyber and Dilithium issues here?

**Comment by bhess** [comment]
> @bhess Would you be able to look at the Kyber and Dilithium issues here?

Yes, I'll take a closer look at the issues.
